[build-system]
requires = [
  "setuptools",
  "ninja",
  "cmake"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
environment = {
  CMAKE_ARGS = "-DCMAKE_C_COMPLIER=\\\"gcc\\\" -DCMAKE_CXX_COMPLIER=\\\"g++\\\" -DCMAKE_CUDA_COMPLIER=\\\"nvcc\\\""
  cuda="12.9"
  temp="/tmp/cuda-temp"
}
xbuild-tools = ["cmake", "ninja"]

[tool.cibuildwheel.linux]
before-all = [
  "chmod +x {package}/tensor-array-repo/Tensor-Array/scripts/actions/install-cuda-rhel.sh",
  "dnf -y install redhat-lsb-core wget",
  "{package}/tensor-array-repo/Tensor-Array/scripts/actions/install-cuda-rhel.sh"
]
xbuild-tools = ["cmake", "ninja"]
