[build-system]
requires = [
  "setuptools>=42",
  "ninja",
  "cmake>=3.18,<3.29"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
environment.cuda = "12.9"
environment.temp = "/tmp/cuda-temp"
environment.CUDA_PATH = "/usr/local/cuda-${cuda}"
environment.PATH = "${PATH}:${CUDA_PATH}/bin"
environment.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${CUDA_PATH}/lib:${CUDA_PATH}/lib64"
xbuild-tools = ["cmake", "ninja"]

[tool.cibuildwheel.linux]
before-all = [
  "chmod +x tensor-array-repo/Tensor-Array/scripts/actions/install-cuda-rhel.sh", 
  "dnf -y install redhat-lsb-core wget",
  ". tensor-array-repo/Tensor-Array/scripts/actions/install-cuda-rhel.sh"
]
xbuild-tools = ["cmake", "ninja"]
