[build-system]
requires = [
  "setuptools",
  "ninja",
  "cmake"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
xbuild-tools = ["cmake", "ninja"]

[tool.cibuildwheel.linux]
before-all = [
  "chmod +x {package}/tensor-array-repo/Tensor-Array/scripts/actions/install-cuda-ubuntu.sh",
  "{package}/tensor-array-repo/Tensor-Array/scripts/actions --cuda=12.9 --temp=/tmp/cuda-temp"
]
xbuild-tools = ["cmake", "ninja"]
