[build-system]
requires = [
  "setuptools",
  "ninja",
  "cmake"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
environment = { cuda="12.9", temp="/tmp/cuda-temp" }
xbuild-tools = ["cmake", "ninja"]

[tool.cibuildwheel.linux]
before-all = [
  "chmod +x {package}/tensor-array-repos/Tensor-Array/scripts/actions/install-cuda-rhel.sh",
  "dnf -y install lsb-release wget",
  "{package}/tensor-array-repos/Tensor-Array/scripts/actions/install-cuda-rhel.sh"
]
xbuild-tools = ["cmake", "ninja"]
