[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "TensorArray"
version = "0.0.1a"
authors = [
  { name="TensorArray-Creators", email="noob_taken@outlook.com" },
]
description = "A machine learning package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Environment :: GPU :: NVIDIA CUDA :: 12",
]

[project.urls]
Homepage = "https://github.com/BigNoobWasTaken/TensorArray-Python"
Issues = "https://github.com/BigNoobWasTaken/TensorArray-Python/issues"
